// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Cu4e2qhBcS7yvWMjOnjtPaxjQ6m3oWk',
    appId: '1:193867110649:android:dae8058556d0a71a6e2a28',
    messagingSenderId: '193867110649',
    projectId: 'wc2026-dfb10',
    storageBucket: 'wc2026-dfb10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9bnxjztLHeTq95tLyQEpCm3xK7IOPO0',
    appId: '1:193867110649:ios:06233e80d9c79bb86e2a28',
    messagingSenderId: '193867110649',
    projectId: 'wc2026-dfb10',
    storageBucket: 'wc2026-dfb10.firebasestorage.app',
    iosBundleId: 'com.sedhamza.wc2026',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Cu4e2qhBcS7yvWMjOnjtPaxjQ6m3oWk',
    appId: '1:193867110649:web:dae8058556d0a71a6e2a28',
    messagingSenderId: '193867110649',
    projectId: 'wc2026-dfb10',
    storageBucket: 'wc2026-dfb10.firebasestorage.app',
  );
}
